import type { Metadata } from "next";
import { Geist, Geist_Mono, League_Spartan, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import MovingBackground from "./components/ui/MovingBackground";
import BottomBlur from "./components/ui/BottomBlur";
import GradualBlurMemo from "./components/ui/GradualBlur";
import Footer from "./components/Footer";
import CursorFollower from "./components/ui/CursorFollower";
import Lenis from "lenis";
import SmoothScrollProvider from "./components/ui/SmoothScrollProvider";

const league_spartan = League_Spartan({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const poppins = Poppins({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-arp="">
      <body className={`${league_spartan.variable} antialiased bg-black`}>
        <CursorFollower />
        <MovingBackground />
        <Navbar />
        {/* {children} */}
        <SmoothScrollProvider>{children}</SmoothScrollProvider>
        <Footer />
      </body>
    </html>
  );
}
