import type { Metadata } from "next";
import { Geist, Geist_Mono, League_Spartan, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import MovingBackground from "./components/ui/MovingBackground";
import BottomBlur from "./components/ui/BottomBlur";

const league_spartan = League_Spartan({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const poppins = Poppins({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-arp="">
      <body className={`${league_spartan.variable} antialiased`}>
        <MovingBackground />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
